modLoader="javafml" # 必填，使用 Forge 加载器
loaderVersion="[47,)" # 必填，Forge 1.20.1 及以上
license="MIT"
# 出现问题时的 issue 跟踪地址
# issueTrackerURL="https://github.com/dongge0210/Enclosed-Space-Render-Culling/issues"

[[mods]] # 必填，mod 列表
modId="enclosed_culling" # 必填，mod 唯一ID（小写、下划线）
version="1.0.0" # 必填，mod 版本
displayName="封闭空间渲染优化 EnclosedSpaceRenderCulling" # 必填，mod显示名
displayURL="https://github.com/dongge0210/Enclosed-Space-Render-Culling"
logoFile="logo.png"
authors="dongge0210"
# description 支持多行
description = '''
优化封闭房间内的渲染和方块实体tick，极大节省你的GPU与CPU性能！
Enclosed space render culling for Minecraft 1.20.1 Forge.
集成房间-门可见性、机械动力等mod的BlockEntity tick优化。
'''

# MIXIN配置（声明mixin json，Forge自动加载，推荐加上）
[[mixins]]
config = "mixins.enclosedculling.json"

# 依赖关系
[[dependencies.enclosed_culling]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.enclosed_culling]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

# 如需兼容机械动力等mod，可加如下声明（可选）
[[dependencies.enclosed_culling]]
    modId="create"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

# [[dependencies.enclosed_culling]]
#     modId="mekanism"
#     mandatory=false
#     versionRange="[*]"
#     ordering="AFTER"
#     side="BOTH"

# [[dependencies.enclosed_culling]]
#     modId="thermal"
#     mandatory=false
#     versionRange="[*]"
#     ordering="AFTER"
#     side="BOTH"