modLoader="javafml" # 必填,使用 Forge 加载器
loaderVersion="[47,)" # 必填,Forge 1.20.1 及以上
license="MIT"
# 出现问题时的 issue 跟踪地址
# issueTrackerURL="https://github.com/dongge0210/Enclosed-Space-Render-Culling/issues"

[[mods]] # 必填,mod 列表
modId="${mod_id}" # 必填,mod 唯一ID（小写、下划线）
version="${mod_version}" # 必填,mod 版本
displayName="${mod_name}" # 必填,mod显示名
displayURL="https://github.com/dongge0210/Enclosed-Space-Render-Culling"
logoFile="logo.png"
authors="${mod_authors}"
# description 支持多行
description = '''${mod_description}'''

# 依赖关系
[[dependencies.enclosed_culling]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.enclosed_culling]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

# Create 依赖配置 - 可选依赖
[[dependencies.enclosed_culling]]
    modId="create"
    mandatory=false
    versionRange="[6.0.6,6.1.0)"
    ordering="AFTER"
    side="BOTH"

# Flywheel 依赖 - 可选依赖，Create 附属
[[dependencies.enclosed_culling]]
    modId="flywheel"
    mandatory=false
    versionRange="[1.0.4,1.1.0)"
    ordering="AFTER"
    side="BOTH"

# Ponder 依赖 - 可选依赖，Create 附属
[[dependencies.enclosed_culling]]
    modId="ponder"
    mandatory=false
    versionRange="*"
    ordering="AFTER"
    side="BOTH"

# [[dependencies.enclosed_culling]]
#     modId="mekanism"
#     mandatory=false
#     versionRange="[*]"
#     ordering="AFTER"
#     side="BOTH"

# [[dependencies.enclosed_culling]]
#     modId="thermal"
#     mandatory=false
#     versionRange="[*]"
#     ordering="AFTER"
#     side="BOTH"